# Generated by Django 4.1.5 on 2023-01-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpaapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='transaction date')),
                ('transaction_type', models.TextField(max_length=6)),
                ('note', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpaapi.pgaccounts')),
            ],
        ),
    ]
