# Generated by Django 4.1.5 on 2023-01-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpaapi', '0002_pgtransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='balance_date')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpaapi.pgaccounts')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pgbalance',
            constraint=models.UniqueConstraint(fields=('account_id', 'date'), name='balancedateconstraint'),
        ),
    ]
